# Generated by Django 4.0.4 on 2022-04-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pen', 'pending'), ('comp', 'complete')], default='pen', max_length=4)),
                ('client_user', models.ForeignKey(limit_choices_to={'user_type': 'cln'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('employee_user', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'emp'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
